### ISSUE TITLE
Just stopping by

### ISSUE THREAD

**Issue by MatthewBooth** [SebiTimeWaster/G213Colors#1]
Apologies for the non-issue issue...

Just popping by to say thanks a bunch for this, and @JeroenED as well for the GUI and service. Saved me a bunch of time digging through documentation to achieve this myself.

I do dual boot with Windows but as you noticed changing the colour doesn't stick without the apps. I use Ubuntu 99% of the time anyway though, so this has been fantastic!

Cheers :)

Matt

**Comment by JeroenED** [comment]
Hi Matthew,

Sorry for the late reply. It's been a great pleasure reading this. However, credit to the right persons as it's not actually me who created the GUI but @derEisele who created the GUI. Myself I'm only responsible for the makefile and service.

But in my opinion, this is what open source is all about. Creating one piece of software and others putting their thoughts on what should make it better.

(FYI: you might have noticed that the after sleeping or suspending the colors are reset again. Not anymore in my branch ;) )

**Comment by SebiTimeWaster** [comment]
You are welcome Matthew, it always makes me happy to see that people are using my stuff!

(funny, github didn't inform me about this issue, wtf?)

**Comment by SebiTimeWaster** [comment]
@JeroenED on my setup i don't have the sleep color reset problem because i use a KVM switch witch keeps the keyboard active even when no computer is running...

**Comment by dereisele** [comment]
Hello there,

I'm also happy to see other people enjoying our project. As @JeroenED mentioned before, I think open source is all about piecing together different skills and ideas to make a great and useful piece of software.
