### ISSUE TITLE
udev rule tip

### ISSUE THREAD

**Issue by drake127** [SebiTimeWaster/G213Colors#13]
Hi,

I couldn't make udev rule working properly because my multimedia keys would stop working after colors were set. By adding just idVendor and idProduct to udev rule, it gets hit three times (device and keyboard+multimedia interfaces). Setting colors takes multimedia interface off, sets colors and then attaches it back. This triggers udev again for attaching multimedia interface and ends up in infinite loop.

I had to limit the rule so that only root device triggers the script
```
ACTION=="add",        KERNEL=="event[0-9]*", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c336", RUN+="/usr/local/bin/G213Colors.sh 4F7F9F"
```

However, I couldn't make it work with ATTRS, so I moved the necessary check to the script itself:
```
#!/bin/sh

[ "${ID_USB_INTERFACE_NUM}" == "00" ] || exit
exec /usr/bin/python /usr/local/bin/G213Colors.py -c $1
```

Maybe somebody can create a more elegant solution but this one works and I believe it should be documented as it took me several hours to figure out.

**Comment by SebiTimeWaster** [comment]
this is my udev rule, everything works after it matches:

`ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c336", ATTR{product}=="Gaming Keyboard G213", RUN+="/usr/local/bin/udev_g213"`

maybe try that one.

**Comment by drake127** [comment]
Yours is certainly better and I think you don't need ATTR{product} because SUBSYSTEM=="usb" is enough for me.

`ACTION=="add", SUBSYSTEM=="usb", ATTRS{idVendor}=="046d", ATTRS{idProduct}=="c336", RUN+="/usr/bin/python /usr/local/bin/G213Colors.py -c 4F7F9F"`

👍

**Comment by SebiTimeWaster** [comment]
i added the udev rule info.
