### ISSUE TITLE
How can I make the profile persistent?

### ISSUE THREAD

**Issue by WunschK** [SebiTimeWaster/G213Colors#15]
Hi there, 

I am on the following system:
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.11.0-41-generic
OS Type: 64-bit
Processors: 8 × Intel® Core™ i5-10210U CPU @ 1.60GHz
Memory: 14,9 GiB

and have just installed the script and it works up until a reboot. 
I have tried added the service as suggested [here](https://github.com/JeroenED/G213Colors). However, I do not get the pre-reboot-status that I want. 

Do u have any idea on how to get this to work? 

all the best, 
K

**Comment by SebiTimeWaster** [comment]
The keyboard does not have the ability to save the settings, that was the reason i wrote this script.

Just run the script on boot or when the keyboard is plugged in via udev rules.
