### ISSUE TITLE
Some issues in g213colors-gui

### ISSUE THREAD

**Issue by gark81** [SebiTimeWaster/G213Colors#2]
Hi,
I'm a newbie in programming, and i try to set your project for set led light of logitech mouse G203 Prodigy without success.

when i've compiled and install G213Colors, if i launch it from terminal, i get these issues
*****************************************************************************************
*****************************************************************************************
1-
File "/usr/bin/g213colors-gui", line 50
    myG.saveData(myG.cycleCommand.format(str(format(self.sbGetValue(self.sbCycle), '04x'))))
                                                                                           ^
TabError: inconsistent use of tabs and spaces in indentation

***>>> i've edited "g213colors-gui" line 50, deleting Tab space and do spaces.
*****************************************************************************************
*****************************************************************************************
2- 
  File "/usr/bin/g213colors-gui", line 150
    print command
                ^
SyntaxError: Missing parentheses in call to 'print'

***>>> i've edited line 150 as this   -->> print (command)

**Comment by dereisele** [comment]
I'm working on this problem and feature request. Untill then, you can check out my old [testing branch](https://github.com/derEisele/G213Colors/tree/testing) with experimental G203 support. Run g203.py as root to set color.

**Comment by gark81** [comment]
THANKS!!
it works!
Great Job!

**Comment by dereisele** [comment]
You're welcome! My version now supports the G213 keyboard and the G203 mouse and allows you to set the illumination for both devices at once.

**Comment by SebiTimeWaster** [comment]
sounds nice! maybe i should add control codes for my G9, even though it's a bit old...

@gark81 on issues with the gui you can open an issue on @derEisele repo.
