### ISSUE TITLE
Pipe error when ctrl_transfer is called

### ISSUE THREAD

**Issue by giomini** [SebiTimeWaster/G213Colors#3]
Hi, I found this project now that I am working on something very similar for my G510 keyboard. 
After .detach_kernel_driver, like you, I also send a .ctrl_transfer, but I always get "Pipe error".
It happens the same when I use your script (duly modified). Have you ever encountered this error? How did you manage to solve it?

Thank you

**Comment by SebiTimeWaster** [comment]
hi, 
no i never saw that.

one small question: did you sniff the command codes for your G510 and added them to my script or did you try to use the already existing codes? 

if the latter i can tell you with 95% certainty without even looking deeper into it that the control codes are not compatible between G Models.

**Comment by giomini** [comment]
Hi, thank you for your reply.
I sniffed the packet on windows when the keyboard talked to the Logitech driver and changed some codes in your script. Unfortunately I haven't been able to do much...
By the way I just found this project https://github.com/madscientist42/G15Interface which works relying on HID API. It is in c++, so it's different from yours, but it can be interesting for you too.  :)

**Comment by SebiTimeWaster** [comment]
curious. my only guess left would be that one of the parameters/ids between line 33 and 39 is wrong (for your keyboard).
