### ISSUE TITLE
It doesn't save configuration after shutdown

### ISSUE THREAD

**Issue by MasterSergius** [SebiTimeWaster/G213Colors#5]
First of all, thanks for great script. The most important issue for me - it works until shutdown. So, I need to re-run this script each time I turn on my computer.

**Comment by agurenko** [comment]
It's not really an issue with a script itself. This keyboard does not have on-board memory to store settings. Even on Windows it just reapplies settings from the app on system start-up, so you can basically achieve it by doing same thing (cron, startup scripts etc.)

**Comment by SebiTimeWaster** [comment]
thanks for answering, @agurenko !
i will expand the readme to include this information.
